account/urls.py
from  django.conf.urls import url
from django.contrib.auth import views as auth_views
from account.views import Signup

urlpatterns=[
    url(r'^signup/$',Signup,name='signup'),
    url(r'^login/$',auth_views.login,{'template_name':'signin.html'},name='login'),
    url(r'^logout/$',auth_views.logout,{'next_page':'home'},name='logout'),

    ]

prasundjango/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from todo.views import home,todolist

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home,name='home'),
    url(r'^todos/$',todolist,name='todolist'),
    url(r'^todos/',include('todo.urls',namespace='todo')),#mapping the apps url to the app
    url(r'^acc/',include('account.urls'))
]

todo/urls.py
from django.conf.urls import url

from todo.views import todoadd,todoedit,todolist,about,contact,tododelete

urlpatterns=[
    # urlbar name , function name , html page name
    url(r'^$',todolist,name='todolist'),
    url(r'^add/$',todoadd,name='todoadd'),
    # url(r'^home/$',home,name='home'),
    url(r'^contact/$',contact,name='contact'),
    # url(r'^edit/(?P<pk>\d+)/$',todoedit,name='todoedit'),
    # url(r'^delete/(?P<pk>\d+)/$',tododelete,name='tododelete'),
    
    
    url(r'^about/$',about,name='about'),
    url(r'^edit/(?P<pk>\d+)/$',todoedit,name='todoedit'),
    url(r'^delete/(?P<pk>\d+)/$',tododelete,name='tododelete'),


]
# • ^ for the beginning of a text
# • $ for the ending of a text
# • \d for a digit 
# • + to inform the previous item should be repeated at least once(kam se kam ek br to wo data hona chahiye)
# • ()to capture part of a pattern
# • ? zero or one of the previous expression (zero ya 1 means ya to data h ya nahi hai)
# • * zero or more of the previous expression
# "P" path k liye likha jata hai
# pk is the primary key of database

account/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title=models.CharField(max_length=255)
    description=models.TextField()
    name=models.CharField(max_length=200)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)


class Contact(models.Model):
    name=models.CharField(max_length=255)
    email=models.CharField(max_length=200)
    mobile=models.CharField(max_length=15)
    query=models.CharField(max_length=255)

todo/forms.py
from django import forms #importing django inbuilt form
from todo.models import Contact, Todo #attatching table where todo is app name and model is pyfilename
# and importing Todo class or table from pyfile

# a form structure for user entry

class TodoForm(forms.ModelForm): #Modelform user se entry leta h
    class Meta: # meta is for multiple inputs
        model=Todo #assigining the table
        fields={"title","description","name"} #attatching the fields from models.py with form

class TodoContact(forms.ModelForm):
    class Meta:
        model=Contact
        fields={"name","email","mobile","query"}

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login
# Create your views here.
def  Signup(request):
    signupform=UserCreationForm(request.POST or None)
    if signupform.is_valid():
        signupform.save()
        email=signupform.cleaned_data.get('email')
        username=signupform.cleaned_data.get('username')#getting the vlaue from user for username
        raw_password=signupform.cleaned_data.get('password1')#getting the value from user for password
        user=authenticate(email=email,username=username,password=raw_password)#checking wethaer password or username is equal or not acc to database
        login(request,user)#if username and password are equal then it will login
        return redirect('todolist')# and redirect to feedback page
    return render(request,'signup.html',{'form':signupform})#otherwise it will be at the same page of signup

todo/views.py
from django.shortcuts import render,redirect,get_object_or_404
from todo.models import Todo # from models.py
from todo.forms import TodoForm # from forms.py
from todo.forms import TodoContact
from todo.models import Contact
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    return render(request,'home.html')
@login_required
def contact(request):
    contactform=TodoContact(request.POST or None) #Data input from user 
    if contactform.is_valid():
        contactform.save()
        return redirect('home') 
        # redirect routes to the next page
        # render connects backend to front end vicea versa
    return render(request,'contact.html',{'form':contactform})
    
@login_required
def about(request):
    return render(request,'about.html')
@login_required
def todoadd(request):
    todoform=TodoForm(request.POST or None) #Data input from user 
    if todoform.is_valid():
        todoform.save()
        return redirect('todolist') 
        # redirect routes to the next page
        # render connects backend to front end vicea versa
    return render(request,'todoadd.html',{'form':todoform})
    # form key entry leta hai user se
@login_required   
def todolist(request):
    allfeedback=Todo.objects.all() #Fetching the data from database db.sqlite(file)
    return render(request,'todolist.html',{'todos':allfeedback})
    #todos key entry ko show karega front end me all feedback wale page me

@login_required
def todoedit(request,pk):
    todo=get_object_or_404(Todo,pk=pk)
   # instance todo due to this data is alredy inserted in entry boxes todoadd.html
    todoform=TodoForm(request.POST or None,instance=todo)

    if todoform.is_valid():
        todoform.save()
        return redirect('todolist')
    return render(request,'todoadd.html',{'form':todoform})#todoadd page will get open
@login_required
def tododelete(request,pk):
    todo=get_object_or_404(Todo,pk=pk)
    
    if request.method=='POST':
        todo.delete()
        return redirect('todolist')
    return render(request,'tododelete.html',{'todo':todo})

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Livewire Indore||Institue for Technology</title>
    <link rel="shortcut icon" href="https://www.livewireindia.com/favicon.ico" type="image/x-icon" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    {% include 'navbar.html' %}
    {%block content%}

    {%endblock%}
    {% include 'footer.html' %}
</body>

</html>

templates/contact.html
{%extends 'base.html'%}
{%block content%}
<style>
    input{border-style: none;text-align: center;}
</style>
<!-- ************************ map ****************************** -->
<!-- first go maps and directions info website 
then area calculator
 then create your map option
 then give address and name
 then copy html code -->
<div style="width: 100%; height: 500px; background-image: url('https://lh3.googleusercontent.com/9zE3StG50FuHs9PCo6kMTIhWKyIc3vJ2JqxPZEgaKc8WQ2vzAyWR4wqYYhMZ7zkhc0C893COYflGKt70Sb15e4gg7eI=w640-h400-e365-rj-sc0x00ffffff');background-size:100% 100%; " class="row" >
    <div style="width: 50%;" class="column">
        <div style="width: 100%;"><iframe width="100%" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=Rewa,Madhya%20pradesh+(PB%20MALL)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"><a href="https://www.gps.ie/sport-gps/">gps watches</a></iframe></div>

    </div>
    <div class="column">
        <div style=" position: absolute; padding-top: 2%; background-color: rgb(201, 196, 196);width:25% ; height:400px;margin-left: 10%; border-radius: 10% ; " >
        <form style="text-align: center;margin-top:50px ;"method="post">
            {%csrf_token%}
            {{form.as_p}}
            <!-- <h4 align="center">Enquiry form</h4><br><br>
            <input type="text" placeholder="Name" class="text"><br><br>
            <input type="text" placeholder="Email" class="text"><br><br>
            <input type="text" placeholder="Mobile" class="text"><br><br>
            <input type="text" placeholder="Your Query" class="text"><br><br>
            <input style="width:56%;" type="button" class="btn btn-primary" value="Submit"> -->
            <button style="width:56%;" class="btn btn-primary"  type="submit">Submit</button>
        </form>
    </div>
    </div>
</div>
{%endblock%}

templates/footer.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        i:hover {
            color: rgb(112, 112, 129);
        }

        .row:after {
            content: "";
            display: table;
            clear: both;

        }

        .column {
            float: left;
            width: 33.3%;
            margin-bottom: 3%;
            margin-top: 3%;
        }
        
    </style>

</head>

<body>

    <div class="row" style="background-color: black;color: white;">
        <div class="column">
            <h4 style="margin-left: 10%; margin-top: 3%;">ABOUT LIVEWIRE</h4><br>
            <p align="left" style="text-align: justify;width:80%;margin-left:10%;">LIVEWIRE promote niche training in
                IT, Electronics & Electricals creating experts for emerging technology industries and specialist
                technology jobs. A part of CADD Centre, which is Asia's largest CAD/CAM/CAE training institute, LIVEWIRE
                is present in 100 locations across India and 8 International Locations.</p>

        </div>
        <div class="column">
            <form style="margin-left: 10%;">
                <h4 style="margin-top: 3%;">NEWSLETTER</h4><br>
                <input type="text" placeholder="Name"><br><br>
                <input type="text" placeholder="Email Address"><br><br>
                <button class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="column">
            <h4 style="margin-top: 3%;">CONTACT INFO</h4><br>
            <p><i class="fa-solid fa-phone"></i>&nbsp;&nbsp; 1800-425-0220</p>
            <p><i class="fa-solid fa-envelope"></i>&nbsp;&nbsp; info@livewireindia.com</p>
            <span><i class="fa-solid fa-map"></i>&nbsp;&nbsp;</span><span style="width: 50%; ">1st Floor, K.R. Ahamed
                Sha office complex, No. 25, Dr. Radhakrishnan Salai, Mylapore,
                <br> Chennai - 600 004,<br>
                Tamil Nadu, India.</span>





        </div>
    </div>

    <footer class="footer bg-dark">.
        <div class="row">
            <div class="col-xs-6 col-md-3 container" style="padding-bottom: 30px;">
                <span class="text-muted" style="font: white;">LIVEWIRE - All rights reserved &copy; 2019</span>


            </div>
            <div class="col-xs-6 col-md-3 container">

                <span><a href="" style="text-decoration: none; color: white;"><i class="fa-brands fa-facebook-square"
                            style="margin-left: 5%; font-size: 30px; "></i></a></span>
                <span><a href="" style="text-decoration: none; color: white;"><i class="fa-brands fa-linkedin"
                            style="margin-left: 5%; font-size: 30px; "></i></a></span>
                <span><a href="" style="text-decoration: none; color: white;"><i class="fa-brands fa-twitter-square"
                            style="margin-left: 5%; font-size: 30px; "></i></a></span>
                <span><a href="" style="text-decoration: none; color: white;"><i class="fa-brands fa-instagram"
                            style="margin-left: 5%; font-size: 30px; "></i></a></span>
                <span><a href="" style="text-decoration: none; color: white;"><i class="fa-brands fa-youtube"
                            style="margin-left: 5%; font-size: 30px; "></i></a></span>



            </div>

        </div>
    </footer>


</body>

</html>

templates/footer1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .row:after{
            content:"";
            display:table;
            clear:both;
           
        }
        .column{
            float:left;
            width:33.3%;
        }
    </style>
</head>
<body>
    <div class="row" style="background-color: black;color: white;">
        <div class="column">
            <h1 style="margin-left: 10%;">About Livewire</h1>
            <p align="left" style="text-align: justify;width:80%;margin-left:10%;">LIVEWIRE promote niche training in IT, Electronics & Electricals creating experts for emerging technology industries and specialist technology jobs. A part of CADD Centre, which is Asia's largest CAD/CAM/CAE training institute, LIVEWIRE is present in 100 locations across India and 8 International Locations.</p>

        </div>
        <div class="column">
            <form style="margin-left: 10%;">
                <h1 >Newsletter</h1>
                <input type="text" placeholder="Name"><br><br>
                <input type="text" placeholder="Email Address"><br><br>
                <button  class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="column">
            <h1>CONTACT INFO</h1>
             <p><i class="fa-solid fa-phone"></i>&nbsp;&nbsp; 1800-425-0220</p> 
             <p><i class="fa-solid fa-envelope"></i>&nbsp;&nbsp; info@livewireindia.com</p>
             <span><i class="fa-solid fa-map"></i>&nbsp;&nbsp;</span><span style="width: 50%;">1st Floor, K.R. Ahamed Sha office complex, No. 25, Dr. Radhakrishnan Salai, Mylapore,
             Chennai - 600 004,<br>
             Tamil Nadu, India.</span>
                
                
               
            
        </div>
    </div>
      

</body>
</html>

templates/home.html
{% extends 'base.html'%}
{%block content%}
<style>
    .butim{ height: 200px; width: 200px; background-size: 100% 100%;}
</style>
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://www.livewireindia.com/images/banner/ec-counsil-home.jpg" class="d-block w-100" height="400px" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://www.livewireindia.com/images/content/bg/01.jpg" class="d-block w-100" height="400px" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://www.livewireindia.com/images/course/partners.png" class="d-block w-100" height="400px" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <h1 align="center">Trending Courses</h1>
  <div class="row" style="margin-left:9%; margin-right: 7%;">
    <div class="col-xs-6 col-md-3">
      <a href="#" class="thumbnail">
        <button class="butim" style=" background-image:url('https://149695847.v2.pressablecdn.com/wp-content/uploads/2019/10/python-1.jpg') ;" ></button><br>        
        </a>
        <span style="margin-left:60px ; text-decoration: solid; font-family:Arial, Helvetica, sans-serif ; "  > Python </span>
    </div>
    <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <button class="butim" style=" background-image:url('https://media.steelkiwi.com/media/filer_public_thumbnails/filer_public/67/71/6771ac15-31e4-4526-8678-e62189d44727/et1-min.png__170x240_q85_crop-smart_subsampling-2_upscale.png') ;" ></button><br>        
          </a>
          <span style="margin-left:60px ; text-decoration: solid; font-family:Arial, Helvetica, sans-serif ; "  > Django </span>
      </div>
      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <button class="butim" style=" background-image:url('https://www.oxfordwebstudio.com/user/pages/06.da-li-znate/sta-je-html/sta-je-html.jpg') ;" ></button><br>        
          </a>
          <span style="margin-left:60px ; text-decoration: solid; font-family:Arial, Helvetica, sans-serif ; "  > HTML5 </span>
      </div>
      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <button class="butim" style=" background-image:url('https://cdn.neow.in/news/images/uploaded/2018/12/1544525547_javascript_jquery_story.jpg') ;" ></button><br>        
          </a>
          <span style="margin-left:60px ; text-decoration: solid; font-family:Arial, Helvetica, sans-serif ; "  > Javascript </span><br>
          <span style="margin-left:60px ; text-decoration: solid; font-family:Arial, Helvetica, sans-serif ; "  > & jquery </span>
      </div>
    
  </div>
{%endblock%}

templates/navbar.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    
    .marginn {
      margin-left: 18%;
    }

    .logo {
      width: 200px;
      height: 60px;
      margin-top: 10px;
    }
  </style>

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="http://127.0.0.1:8000/"><img class="logo"
          src="https://www.livewireindia.com/livehack/images/livewirelogo.png" alt=""></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse marginn" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="http://127.0.0.1:8000/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://127.0.0.1:8000/todos/about">AboutUs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://127.0.0.1:8000/todos/add">Add Your Feedback</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://127.0.0.1:8000/todos/">All Feedbacks</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              User
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="http://127.0.0.1:8000/acc/signup">Signup</a></li>
              <li><a class="dropdown-item" href="http://127.0.0.1:8000/acc/login">SignIn</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="http://127.0.0.1:8000/acc/logout">SignOut</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="http://127.0.0.1:8000/todos/contact">Contact</a>
          </li>
        </ul>

      </div>
      <div>
        {%if user.is_authenticated%}
        <p style="color: white;margin-top:7%">Hii, {{user.username}}!!!Welcome<a style="text-decoration:none ;" href="{% url 'logout'%}">&nbsp;&nbsp;&nbsp;Logout</a></p>
        {%endif%}
      </div>
    </div>
    
  </nav>
  

</body>

</html>

templates/navbar1.html
<style>
.nv{
background-color:crimson;}
.nav-link{
    color: white;
}
.p{
    color: yellow;
}
</style>
<nav class="navbar navbar-red  nv">
<a class="nav-link" href="http://127.0.0.1:8000/">Home</a>

<a  class="nav-link" href="http://127.0.0.1:8000/todos/">App Feedback</a>

<a  class="nav-link" href="http://127.0.0.1:8000/todos/add/">Add Your Feedback</a>

<a class="nav-link" href="http://127.0.0.1:8000/todos/contact/">Contact</a>
<a class="nav-link" href="http://127.0.0.1:8000/todos/about/">About</a>

<a class="nav-link" href="http://127.0.0.1:8000/account/signup/">Signup</a>

<a  class="nav-link" href="http://127.0.0.1:8000/account/login/">Login</a>

<div>
{%if user.is_authenticated%}
<p class="p">Hi, {{user.username}}!!Welcome <a href="{%url 'logout' %}">Logout</a></p>
{%endif%}
</div>

<img width="150px" height="50px" src="https://support.livewireindia.com/tmp/images/live_wire_logo.jpg" alt="Livewirelogo">

</nav>

templates/signin.html
{%extends 'base.html'%}
{%block content%}

<div
    style="width: 100%; height: 500px; background-image: url('https://lh3.googleusercontent.com/9zE3StG50FuHs9PCo6kMTIhWKyIc3vJ2JqxPZEgaKc8WQ2vzAyWR4wqYYhMZ7zkhc0C893COYflGKt70Sb15e4gg7eI=w640-h400-e365-rj-sc0x00ffffff');background-size:100% 100%; ">
<!-- absolute rakhne se wo piche wale div ko chhod dega -->
    <div style="margin-top: 8%; position: absolute; padding-top: 2%; background-color: rgb(201, 196, 196);width:25% ; height:300px;margin-left: 38%; border-radius: 10% ; "
        class="container">
        <h4 align="center">Student's Login</h4><br><br>
        <!-- <input style="border-style: none; margin-left: 20%;" type="text" placeholder="Email Address"
            class="text"><br><br>
        <input style="border-style: none; margin-left: 20%;" type="password" placeholder="Password"
            class="text"><br><br> -->
            <form method="post">
                {%csrf_token%}
                {{form.as_p}}
                <button style="margin-left: 20%;width: 58%;" class="btn btn-primary" type="submit" name="login">Signin</button>
            </form>
       
    <br><a style="margin-left: 22%;text-decoration: none; color: black;" href="http://127.0.0.1:8000/todos/signup">Not registered? Sign Up</a>
    </div>
</div>
{%endblock%}

templates/signup1.html
{%extends 'base.html'%}

{%block content%}

<form method="post">
    <h1>Register yourself</h1>
    {%csrf_token%}
    <!--  it is  akind of attribute which redirect the form from backend to frontend -->
    {{form.as_p}}
    <button type="submit" name="signup">Signup</button>


</form>
{%endblock%}

templates/tododelete.html
{%extends 'base.html'%}
{%block content%}
<form method="post">
    {%csrf_token%}
    <p>Are you sure?</p>
    <p>yes i want to delete"{{todo.title}}"</p>
    <button type="submit" name="tododelete">Delete</button>
   
    <!-- name=function ko call krta h -->

</form>
<a href="http://127.0.0.1:8000/todos/"><button>No,Take ME Back....</button></a>
{%endblock%}

templates/todolist.html
{% extends 'base.html'%}

{%block content%}
<style>
    table,th,td,tr{border: 2px solid black; text-align: center;}
    table{width: 100%;}
    td,th{height: 50px;}
</style>
<table id="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Name</th>
            <th>Created At</th>
            <th>Updated At</th>
            <th>Edit/Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for todo in todos%}
        <tr>
            <td>{{todo.title}}</td>
            <td>{{todo.description}}</td>
            <td>{{todo.name}}</td>
            <td>{{todo.created_at}}</td>
            <td>{{todo.updated_at}}</td>
            <td>
                <!-- todo.id is used to show the primay key at the url while deleting or updating the data -->
                <a href="{%url 'todo:todoedit' todo.id%}"><button>update</button></a>
                <a href="{%url 'todo:tododelete' todo.id%}"><button>delete</button></a>
            </td>
        </tr>
        {%endfor%}
    </tbody>
</table>
<br>
<button style="width:200px;height:40px;position:relative;left:40%;right:0;top:0;bottom:0;margin:auto;"><a id="downdlink" onclick="exportF(this)">Download Into excel</a></button>
<br><br>
    <script>
        function exportF(elem)
        {
            var table=document.getElementById("table");//connecting becak to front end
            var html=table.outerHTML;//gettong the output from html
            var url='data:application/vnd.ms-excel,' +escape(html);//connecting url to html
            elem.setAttribute("href",url);//accessing the url
            elem.setAttribute("exportiii.xls");//defining the file name
            return false;    // in case of error nothing will gate        
        }
    </script>














{%endblock%}